### ISSUE TITLE
Support HTTP API functions

### ISSUE THREAD

**Issue by kernwig** [ar90n/serverless-plugin-export-endpoints#4]
Add support for API Gateway HTTP APIs, per https://www.serverless.com/framework/docs/providers/aws/events/http-api/

I can submit a pull request, if there's anyone here to accept it. (Last update is four years ago, so don't know if this is being maintained.)

**Comment by ar90n** [comment]
Hi @kernwig 
Thanks for your comment and interest in this project! As you said, this project hasn't been maintained. But I welcome your PR.

**Comment by kernwig** [comment]
@ar90n How do we get a version bump and release published to NPM?

**Comment by ar90n** [comment]
@kernwig 
I'm so sorry. I forgot to publish a new version to NPM. I've just published it. So please try it!

**Comment by kernwig** [comment]
Works!
